from typing import Any

def ecdh_p256(peer_x: bytes, peer_y: bytes) -> tuple[bytes, bytes, bytes]: ...
def aes_cbc_decrypt(key: bytes, iv: bytes, ciphertext: bytes) -> bytes: ...
def aes_cbc_encrypt_v1(key: bytes, plaintext: bytes) -> bytes: ...
def aes_cbc_decrypt_v1(key: bytes, ciphertext: bytes) -> bytes: ...
def aes_cbc_encrypt_v2(key: bytes, plaintext: bytes) -> bytes: ...
def aes_cbc_decrypt_v2(key: bytes, data: bytes) -> bytes: ...
def hkdf_sha256(salt: bytes, ikm: bytes, info: bytes, length: int) -> bytes: ...
def kdf_v1(z: bytes) -> bytes: ...
def kdf_v2(z: bytes) -> bytes: ...

class NativePinProtocol:
    version: int
    def __init__(self, version: int) -> None: ...
    def encapsulate(
        self, peer_x: bytes, peer_y: bytes
    ) -> tuple[dict[int, Any], bytes]: ...
    def encrypt(self, key: bytes, plaintext: bytes) -> bytes: ...
    def decrypt(self, key: bytes, ciphertext: bytes) -> bytes: ...
    def authenticate(self, key: bytes, message: bytes) -> bytes: ...
    def validate_token(self, token: bytes) -> bytes: ...
