def sha256(data: bytes) -> bytes: ...
def hmac_sha256(key: bytes, data: bytes) -> bytes: ...
def websafe_encode(data: bytes) -> str: ...
def websafe_decode(data: str | bytes) -> bytes: ...
def bytes_eq(a: bytes, b: bytes) -> bool: ...
def aes_gcm_encrypt(
    key: bytes, nonce: bytes, plaintext: bytes, aad: bytes
) -> bytes: ...
def aes_gcm_decrypt(
    key: bytes, nonce: bytes, ciphertext: bytes, aad: bytes
) -> bytes: ...
