class Certificate:
    def __init__(self, der: bytes) -> None: ...
    def public_key_as_cose(self, alg: int) -> dict[int, object]: ...
    def subject_string(self, oid: str) -> str | None: ...
    def subject_is_empty(self) -> bool: ...
    def version(self) -> int: ...
    def extension_value(self, oid: str) -> tuple[bool, bytes] | None: ...
    def basic_constraints_ca(self) -> bool | None: ...
    def extended_key_usage_contains(self, oid: str) -> bool: ...
    def has_subject_alternative_name(self) -> bool: ...
    def issuer_der(self) -> bytes: ...
    def subject_der(self) -> bytes: ...
    def subject_key_identifier(self) -> bytes: ...

def verify_x509_chain(chain: list[bytes]) -> None: ...
