from typing import Callable

class HidDescriptor:
    path: str
    vid: int
    pid: int
    product_name: str | None
    serial_number: str | None
    report_size_in: int
    report_size_out: int

def list_descriptors() -> list[HidDescriptor]: ...

class CtapHidConnection:
    def __init__(self, descriptor: HidDescriptor) -> None: ...
    def write_packet(self, data: bytes) -> None: ...
    def read_packet(self) -> bytes: ...
    def call(
        self,
        cmd: int,
        data: bytes,
        on_keepalive: Callable[[int], None] | None = None,
    ) -> bytes: ...
    @property
    def device_version(self) -> tuple[int, int, int]: ...
    @property
    def capabilities(self) -> int: ...
    @property
    def packet_size(self) -> int: ...
    def close(self) -> None: ...
    def __enter__(self) -> CtapHidConnection: ...
    def __exit__(self, *args: object) -> None: ...
